version: '3'
services:
  db:
    image: kartoza/postgis:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASSWORD}
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 35432:5432
    restart: always

  web:
    build: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: ["bash", "./utils/wait-for-it.sh", "db:5432", "--", "bash",  "./utils/start-server.sh"]
    volumes:
      - .:/code
    ports:
      - "81:8000"
    depends_on:
      - db
    restart: always

